name: CI

on:
  pull_request:
    branches: main

env:
  CAPSTONEONGOING_COGNITO_APPCLIENTID: ${{secrets.CAPSTONEONGOING_COGNITO_APPCLIENTID}}
  CAPSTONEONGOING_COGNITO_POOLID: ${{secrets.CAPSTONEONGOING_COGNITO_POOLID}}
  CAPSTONEONGOING_COGNITO_REGION: ${{secrets.CAPSTONEONGOING_COGNITO_REGION}}
  CAPSTONEONGOING_DATABASE_HOST: ${{secrets.CAPSTONEONGOING_DATABASE_HOST}}
  CAPSTONEONGOING_DATABASE_NAME: ${{secrets.CAPSTONEONGOING_DATABASE_NAME}}
  CAPSTONEONGOING_DATABASE_PASSWORD: ${{secrets.CAPSTONEONGOING_DATABASE_PASSWORD}}
  CAPSTONEONGOING_DATABASE_PORT: ${{secrets.CAPSTONEONGOING_DATABASE_PORT}}
  CAPSTONEONGOING_DATABASE_USERNAME: ${{secrets.CAPSTONEONGOING_DATABASE_USERNAME}}
  CAPSTONEONGOING_JWT_ISSUER: ${{secrets.CAPSTONEONGOING_JWT_ISSUER}}
  CAPSTONEONGOING_JWT_SECRET_KEY: ${{secrets.CAPSTONEONGOING_JWT_SECRET_KEY}}
  CAPSTONEONGOING_JWT_TOKEN_EXPIRE_TIME_IN_MINUTES: ${{secrets.CAPSTONEONGOING_JWT_TOKEN_EXPIRE_TIME_IN_MINUTES}}
  CAPSTONEONGOING_REDIS_HOST: ${{secrets.CAPSTONEONGOING_REDIS_HOST}}
  CAPSTONEONGOING_REDIS_PORT: ${{secrets.CAPSTONEONGOING_REDIS_PORT}}
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
   
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Run
      run: |
        nohup dotnet run --project CapstoneOnGoing -nowarn & sleep 30
      
    - name: Test api
      uses: matt-ball/newman-action@master
      with:
        apiKey: PMAK-62d8cd6723a07f66ddd26dbc-0d9ae225dcdb53cfe4b132e22fbbd60f8d
        collection: d06dcfb4-c609-4c51-8287-9b46a7fd9766
        environment: e38c0ca2-6222-4f92-b451-f12143fdf074
